version: '3.8'

services:
  rag-app:
    build: .
    ports:
      - "8000:8000"  # FastAPI backend
      - "8501:8501"  # Streamlit frontend
    volumes:
      - ./data:/app/data
      - ./vector_store:/app/vector_store
    environment:
      - PYTHONPATH=/app/src
      - TRANSFORMERS_CACHE=/app/data/transformers_cache
    restart: unless-stopped

